### Get tasks 
GET http://localhost:3001/

### Add new task 
POST http://localhost:3001/newcomment HTTP/1.1
Content-Type: application/json

{
  "articleId": "1",
  "userId": "1",
  "comment": "Very good"
}


### Delete task DELETE https://todo-backend-47er.onrender.com/delete/11 HTTP/1.1